on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: Docker meta
          id: docker_meta
          uses: docker/metadata-action@v3
          with:
           images: mtkyes/terraform-gitpod
           
          
        - run: |
             echo ${{steps.docker_meta.outputs.tags}}
             echo ${{steps.decker_meta.outputs.version}}
             echo ${{ github.run_number }}

        # - name: 'Build and push image'
        #   uses: azure/docker-login@v1
        #   with:
        #     login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        #     username: ${{ secrets.REGISTRY_USERNAME }}
        #     password: ${{ secrets.REGISTRY_PASSWORD }}
        # - run: |
        #     docker build . -f .gitpod.Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/terraform-gitpod:${{steps.docker_meta.outputs.tags}}
        #     docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/terraform-gitpod:${{steps.docker_meta.outputs.tags}}
